### ISSUE TITLE
What happens if the component unmounts before promise resolution?

### ISSUE THREAD

**Issue by chmac** [capaj/react-promise#14]
I imagine that if the component is unmounted before the promise has resolved, then there will be a warning about calling `setState()` on a component which does not exist.

I haven't tested, so please disregard this issue if it's not the case. I read about the problem somewhere and was looking at the code here to see if this package addresses the issue.

**Comment by capaj** [comment]
@chmac you have a point. I haven't tested it, but this will indeed cause issues. I've made a small PR, can you tell me if it works for you? #15

**Comment by chmac** [comment]
Looks like it will do the job. 👍

I ended up building something myself with `lifecycle()` from recompose using the same approach. I've also since thrown that all away due to performance issues with PouchDB, so can't easily test this unfortunately.

**Comment by capaj** [comment]
fix released as 2.0.1
