### ISSUE TITLE
Race condition when changing promises during load

### ISSUE THREAD

**Issue by d07RiV** [capaj/react-promise#16]
Consider the following example:

    const timedPromise = (value, delay) => new Promise((resolve, reject) => {
      setTimeout(() => resolve(value), delay);
    });

    class Test extends PureComponent {
      constructor(props) {
        super(props)
        this.state = {promise: timedPromise("Hello 1", 3000)};
        setTimeout(() => {
          this.setState({promise: timedPromise("Hello 2", 1000)});
        }, 1000);
      }

      render() {
        return <Async promise={this.state.promise} pending={<div>Loading...</div>} then={val => <div>{val}</div>}/>;
      }
    }

We set the "Hello 2" promise after "Hello 1", but since the first promise loads slower, it ends up being displayed instead. This is a very common scenario when the user keeps trying to load different resources, and ends up with incorrect state.

**Comment by capaj** [comment]
will add a check there. Thanks for the thorough explanation.

**Comment by capaj** [comment]
@d07RiV what do you think about the proposed fix? Will that suffice?

**Comment by d07RiV** [comment]
It should work as long as all setState operations are resolved in the same order they are initiated in, but the spec doesn't guarantee that. In theory, if the promise is already fulfilled, and somehow `then` callback and its `setState` manages to resolve before the first call to `setState` we could be in trouble, but I doubt that will ever happen.
