### ISSUE TITLE
`pending` prop usage is a bit unintuitive

### ISSUE THREAD

**Issue by andywer** [capaj/react-promise#18]
Hey @capaj,
thanks for providing this useful helper.

I just used it for the first time and did a mistake, that I suppose is quite common:
`then` and `catch` props are functions returning some React node. The `pending` prop instead is supposed to be a React node, not a function.

I get that there is no argument to pass to `pending`, but it would be easier to use if they would all just take a function.

Cheers

**Comment by capaj** [comment]
Hey @andywer thanks for using it! I will make it so that you can use both.
I usually just put some loading spinner into pending so that's why there wasn't an option to put a whole function in. I will add just for the sake of consistency.

**Comment by andywer** [comment]
Cool and thx for the ultra-quick response 😊
