### ISSUE TITLE
Please move webpack-cli to devDeps.

### ISSUE THREAD

**Issue by davejm** [capaj/react-promise#19]
https://github.com/capaj/react-promise/blob/50b3203b85e040c1d5ebe7dfb2140021c1f0b54a/package.json#L70

I get a lot of warnings when installing upstream packages that depend on this one due to the fact that you declare webpack-cli as a runtime dependency. Please move it to devDeps

**Comment by vlucas** [comment]
Ran into the same thing. NPM installed 254 packages because you have `webpack-cli` in your `dependencies`. I promptly uninstalled your package as a result and wrote my own replacement. This needs to be fixed.

**Comment by capaj** [comment]
@vlucas if you're using webpack then these won't go into your bundle anyway, but sure I'll fix this.

**Comment by capaj** [comment]
released in 2.0.3 but NPM is having a bad day so probably wait for tomorrow
