### ISSUE TITLE
Can you also export a named `Async` parameter?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [capaj/react-promise#25]
I'm having problems using `react-promise` with TypeScript because test code running in Jest on Node gets an `undefined` value for `Async` from `import Async from "react-promise";` despite in-browser code via Webpack running fine.

* `react-promise.cjs` ends with `module.exports = Async;`
* `react-promise.es.js` ends with `export default Async;`

...as a result, my unit tests are failing.

Default exports are tricky in general ([a few points here](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html), [and other points here](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad)).

**Comment by capaj** [comment]
oh sorry, I've only spotted your issue just now. Will merge this ASAP.

**Comment by capaj** [comment]
should be released in 2.1.0
