### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by raapperez** [capaj/react-promise#4]
Thank you for the component, nice job.

Can you please use the prop-types package https://www.npmjs.com/package/prop-types to avoid this warning?

Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by capaj** [comment]
thanks for a reminder! I will add that in the next 24 hours.

**Comment by capaj** [comment]
fixed by c16ddb8fed79afffb1e8a83283dc2d27056f5401
